#!/bin/sh
# Script to show cmus song on i3blocks

icon=" "

if pgrep -x "cmus" > /dev/null
then
	# search for line with string, cut the field 3 from 2nd space to the end
	artist=$(cmus-remote -Q | grep ' artist ' | cut -d ' ' -f3-)
	song=$(cmus-remote -Q | grep title | cut -d ' ' -f3-)
	echo "${icon}${artist} - ${song}"
	exit 0
else
	exit 0
fi
