#!/bin/sh

if pgrep -x "cmus" > /dev/null; then
	artist="$(cmus-remote -Q | grep ' artist ' | cut -d ' ' -f3-)"
	song="$(cmus-remote -Q | grep ' title ' | cut -d ' ' -f3-)"
	echo " ${artist} - ${song}"
fi
