#!/bin/sh
#------------------------------
# /etc/X11/xinit/xinitrc
#------------------------------

userresources="${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources"
[ -f "$userresources" ] && xrdb -merge "$userresources"

[ -x /etc/X11/xinit/xinitrc.d/*systemd-user.sh ] &&
    source /etc/X11/xinit/xinitrc.d/*systemd-user.sh

#------------------------------
# Custom Settings
#------------------------------

# Disable MB beep
xset -b

# Autostart
picom -CGb
fehbg &
blueman-applet &
dwmblocks &
unclutter &

# Execute Window Manager
exec dwm

