#!/usr/bin/env bash

shopt -s nullglob

# SXIV options: -a (animated gifs), -b (no bar), -g (window size)
options="-a -b -g 1280x720"

# Open only the selected files
if [[ $# -gt 1 ]]; then
	exec setsid -f sxiv $options "$@"
fi

# Open all image files in the current directory
if [[ ! -f $1 ]]; then
    echo "$0: Argument is not a file" >&2
    exit 1
fi

file=$(basename -- "$1")
dir=$(dirname -- "$1")
arr=()
shift

cd -- "$dir"

for i in *; do
    [[ -f $i ]] || continue
	arr+=("$i")
    [[ $i == $file ]] && n=${#arr[@]}
done

exec setsid -f sxiv -n "$n" $options "${arr[@]}"
