#!/usr/bin/env bash
readonly ID_PREVIEW="preview"

# Play gifs automatically, requires more CPU
#PLAY_GIF="yes"

# Delete preview image after it is drawn, requires more CPU
#AUTO_REMOVE="yes"

# Create temporary working directory if the directory structure doesn't exist
if [[ ! -d "/tmp$PWD/" ]]; then
    mkdir -p "/tmp$PWD/"
fi

function previewclear() {
    declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
        > "$FIFO_UEBERZUG"
}

function fileclean() {
    if [[ -f "/tmp$PWD/$6.png" ]]; then
        rm -f "/tmp$PWD/$6.png"
    elif  [[ -d "/tmp$PWD/$6/" ]]; then
        rm -rf "/tmp$PWD/$6/"
    fi
}

function preview() {
    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
        [path]="$PWD/$6") \
        > "$FIFO_UEBERZUG"
}

function previewvideo() {
    if [[ ! -f "/tmp$PWD/$6.png" ]]; then
        ffmpegthumbnailer -i "$PWD/$6" -o "/tmp$PWD/$6.png" -s 0 -q 10
    fi
    declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
        [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
        [path]="/tmp$PWD/$6.png") \
        > "$FIFO_UEBERZUG"
}

function previewgif() {
    if [[ ! -d "/tmp$PWD/$6/" ]]; then
        mkdir -p "/tmp$PWD/$6/"
        convert -coalesce "$PWD/$6" "/tmp$PWD/$6/$6.png"
    fi
    if [[ ! -z "$PLAY_GIF" ]]; then
        for frame in $(ls -1 /tmp$PWD/$6/$6*.png | sort -V); do
            declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                [path]="$frame") \
                > "$FIFO_UEBERZUG"
            # Sleep between frames to make the animation smooth.
            sleep .07
        done
    else
            declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                [path]="/tmp$PWD/$6/$6-0.png") \
                > "$FIFO_UEBERZUG"
    fi
}

function main() {
    case "$1" in
        "clear") previewclear "$@" ;;
        "clean") fileclean "$@" ;;
        "draw") preview "$@" ;;
        "videopreview") previewvideo "$@" ;;
        "gifpreview") previewgif "$@" ;;
        *) echo "Unknown command: '$@'" ;;
    esac
}

main "$@"
