#!/usr/bin/env bash

# Source Environmental Variables for Cronjob
[[ -r ${SHELL_DOTFILES_DIR:-$HOME/.config/shell}/private_env ]] &&
    source "${SHELL_DOTFILES_DIR:-$HOME/.config/shell}/private_env"

# User Variables
backup_directory="${BACKUP_DIRECTORY:-$HOME/documents/backup}"
if [[ ! -d "$backup_directory" ]]; then
	echo -e "Backup Directory does not exist:\n$backup_directory"
	exit 1
fi

backup_list="$backup_directory/backup_list"
if [[ ! -f "$backup_list" ]]; then
	echo "Backup List could not be found."
	exit 101
fi

date_directory="backup_system_$(date -I)"
if [[ ! -d "$backup_directory/$date_directory" ]]; then
	mkdir -p "$backup_directory/$date_directory"
fi

# Default
while IFS='' read -r line; do
	case "$line" in
		''|\#*) continue ;;
	esac
	eval cp -ru "$line" '"$backup_directory/$date_directory"'
done < "$backup_list"

pacman -Qq > "$backup_directory/$date_directory/arch-all-install"
pacman -Qeq > "$backup_directory/$date_directory/arch-exp-install"
cp -u "$backup_list" "$backup_directory/$date_directory"

tar -C "$backup_directory" \
	-czf "$backup_directory/$date_directory.tar.gz" "$date_directory"
rm -rf "$backup_directory/$date_directory"

