#!/bin/sh

pwlist="$(pass ls | sed '1d;s/^[^[:alpha:]]\+ \+//g')"
choice=$(echo "$pwlist" | dmenu-default-options -i)

if [ -n "$choice" ]; then
    pass -c "$choice" >/dev/null 2>&1
    if [ $? = 0 ]; then
        notify-send -u normal "Copied $choice to clipboard" \
            'Will clear in 45 seconds.'
    else
        notify-send -u critical "Could not copy $choice"
    fi
fi

