#!/bin/sh
# 755 root:root /usr/bin/dmenuexit

# System Options
sysctl="systemctl"
sysopt="Lock\\nExit\\nReboot\\nShutdown"

choice=$(echo -e "$sysopt" | dmenu-default-options -i)

case "${choice,,}" in
    lock)       slock               ;;
    exit)       killall dwm         ;;
    reboot)     $sysctl reboot      ;;
    shutdown)   $sysctl poweroff    ;;
    *)  ;;
esac

