#!/bin/sh

font_type='xft::Bitstream Vera Sans:size=10'
normal_bg='#191b1c'
normal_fg='#bbbbbb'
select_bg='#263238'
select_fg='#eeeeee'

dmenu "$@" -fn "$font_type" \
    -nb "$normal_bg" -nf "$normal_fg" -sb "$select_bg" -sf "$select_fg"

