#!/bin/sh

case "$1" in
    -q) ;;
    -w) exec "$BROWSER" ;;
    -e) ;;
    -r) exec yt-thumbnail ;;
    -a) exec lbry ;;
    -s) ;;
    -d) exec download-links ;;
    -f) exec dmenucalc ;;
    -z) ;;
    -x) ;;
    -c) exec nicotine ;;
    -v) ;;
    -1) ;;
    -2) ;;
    -3) ;;
    -4) ;;
    -5) ;;
    -6) ;;
    -7) ;;
    -8) ;;
    -9) ;;
    -0) exec dmenupass ;;
    *)  ;;
esac

