#!/bin/sh

case "$1" in
	-q)	;;
	-w)	exec "$BROWSER" ;;
	-e)	;;
	-r)	;;
	-a)	;;
	-s) ;;
	-d) exec download-links  ;;
	-f) ;;
	-z) ;;
	-x) ;;
	-c) ;;
	-v) ;;
	-1) ;;
	-2) ;;
	-3) ;;
	-4) ;;
	-5) ;;
	-6) ;;
	-7) ;;
	-8) ;;
	-9) ;;
	-0) ;;
    *)  ;;
esac

