#!/bin/sh
# Find correct Audio Sink for DWM - Volume Control

# Audio Sink Priority: Bluetooth > Audio jack
as=$(pactl list short sinks | grep 'a2dp_sink' | cut -f1)
as=${as:=$(pactl list short sinks | grep 'analog-stereo' | cut -f1)}

case "$1" in
	-m) exec pactl set-sink-volume $as -5%  ;;
	-p) exec pactl set-sink-volume $as +5%  ;;
	*)  exec pactl set-sink-mute $as toggle ;;
esac
