#!/bin/sh

info="\t[f]   Fahrenheit    ↔  [c]   Celsius
\t[lbs] Pounds        ↔  [kg]  Kilograms
\t[oz]  Ounces        ↔  [g]   Grams
\t[foz] Fluid Ounces  ↔  [ml]  Mililiters
\t[gal] Gallons       ↔  [l]   Liters
\t[in]  Inches        ↔  [cm]  Centimeters
\t[fi]  Feet/Inches   ↔  [mc]  Meters/Centimeters
\t[ft]  Feet          ↔  [m]   Meters
\t[mi]  Miles         ↔  [km]  Kilometers"

[ -z $1 ] && echo -e "$info" && exit 2

case "$1$2" in
	*[0-9]f)    fn="(${1%f}-32)*5/9"        ;;
	*[0-9]c)    fn="${1%c}*9/5+32"          ;;
	*[0-9]lbs)  fn="${1%lbs}/2.2046"        ;;
	*[0-9]kg)   fn="${1%kg}*2.2046"         ;;
	*[0-9]oz)   fn="${1%oz}*28.34952"       ;;
	*[0-9]g)    fn="${1%g}/28.34952"        ;;
	*[0-9]foz)  fn="${1%foz}/0.033814"      ;;
	*[0-9]ml)   fn="${1%ml}*0.033814"       ;;
	*[0-9]gal)  fn="${1%gal}*3.785411784"   ;;
	*[0-9]l)    fn="${1%l}/3.785411784"     ;;
	*[0-9]in)   fn="${1%in}*2.54"           ;;
	*[0-9]cm)   fn="${1%cm}/2.54"           ;;
	*[0-9]fi)
		val="${1%fi}"
		fn="${val%.*}*0.3048+${val#*.}*0.0245"
		;;
	*[0-9]mc)
		fn="scale=0;in=${1%mc}/0.0254;ft=in/12;print ft, \".\", (in-12*ft)"
		;;
	*[0-9]ft)   fn="${1%ft}/3.2808"         ;;
	*[0-9]m)    fn="${1%m}*3.2808"          ;;
	*[0-9]mi)   fn="${1%mi}*1.609344"       ;;
	*[0-9]km)   fn="${1%km}/1.609344"       ;;
	*)          echo -e "$info" && exit 2   ;;
esac

printf "%.2f\n" $(echo "$fn" | bc -l)
